# Keep 30 days of apache web server logs in compressed format
/var/log/apache2/*.log {
    rotate 30
    compress
    delaycompress
    missingok
    notifempty
    sharedscripts
    postrotate
        apache2ctl graceful > /dev/null 2>&1 || true
    endscript
}

# Frepple logs are managed by the application itself. They are automatically compressed
# if older than a day and deleted once the allocated disk space is reached (configurable
# with the setting MAXTOTALLOGFILESIZE in /etc/frepple/djangosettings.py)
