#!/bin/bash

set -e

if [ "$1" = "purge" ]; then
  # Remove log directory
  rm -rf /var/log/frepple
fi

if [ "$1" = "remove" ]; then
  ldconfig
  deluser --quiet frepple || true
  delgroup --quiet frepple || true
fi

exit 0
