packages:
  - freppledb/common/frontend
  - freppledb/forecast/frontend
  - freppledb/input/frontend

onlyBuiltDependencies:
  - esbuild
overrides:
  nanoid@<3.3.18: '>=3.3.18 <4.0.0'
  postcss@<=8.5.17: '>=8.5.18 <8.5.22'
  postcss@<=8.5.22: '>=8.5.23'
