#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# frePPLe documentation build configuration file, created by
# sphinx-quickstart on Sat Nov 22 23:39:31 2014.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import sys
import os

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
sys.path.insert(0, os.path.abspath("."))

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = ["frepple", "sphinx_tabs.tabs", "sphinx_sitemap", "sphinx_reredirects"]

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix of source filenames.
source_suffix = ".rst"

# If true, the reST sources are included in the HTML build as _sources/name.
html_copy_source = False

# The encoding of source files.
# source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = "index"

# General information about the project.
project = "frePPLe"
copyright = "2020, frePPLe bv"

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = "development"
# The full version, including alpha/beta/rc tags.
release = "development"

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
# language = None

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
# today = ''
# Else, today_fmt is used as the format for a strftime call.
# today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ["_build", "_templates", "_html"]

# The reST default role (used for this markup: `text`) to use for all
# documents.
# default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
# add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
# add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
# show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# A list of ignored prefixes for module index sorting.
# modindex_common_prefix = []

# If true, keep warnings as "system message" paragraphs in the built documents.
# keep_warnings = False


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = "frepple"

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
# html_theme_options = {}

# Add any paths that contain custom themes here, relative to this directory.
html_theme_path = ["_templates"]

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
# html_title = None

# A shorter title for the navigation bar.  Default is the same as html_title.
# html_short_title = None

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
# html_logo = None

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
html_favicon = "../src/frepple.ico"

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = []

html_permalinks = False

# Add any extra paths that contain custom files (such as robots.txt or
# .htaccess) here, relative to this directory. These files are copied
# directly to the root of the documentation.
# html_extra_path = []

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
# html_last_updated_fmt = '%b %d, %Y'

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
# html_use_smartypants = True

# Custom sidebar templates, maps document names to template names.
# html_sidebars = {}

# Additional templates that should be rendered to pages, maps page names to
# template names.
# html_additional_pages = {}

# If false, no module index is generated.
html_domain_indices = False

# If false, no index is generated.
html_use_index = False

# If true, the index is split into individual pages for each letter.
# html_split_index = False

# If true, links to the reST sources are added to the pages.
html_show_sourcelink = False

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
html_show_sphinx = False

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
html_show_copyright = False

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
# html_use_opensearch = ''

# This is the file name suffix for HTML files (e.g. ".xhtml").
html_file_suffix = ".html"

# Output file base name for HTML help builder.
htmlhelp_basename = "frePPLedoc"

# Add permalinks for each heading and description environment as paragraph signs
html_add_permalinks = ""

# See https://sphinx-tabs.readthedocs.io/en/latest/
sphinx_tabs_disable_css_loading = True
sphinx_tabs_disable_tab_closing = True

# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #'papersize': 'letterpaper',
    # The font size ('10pt', '11pt' or '12pt').
    #'pointsize': '10pt',
    # Additional stuff for the LaTeX preamble.
    #'preamble': '',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    ("index", "frePPLe.tex", "frePPLe Documentation", "frePPLe bv", "manual")
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
# latex_logo = None

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
# latex_use_parts = False

# If true, show page references after internal links.
# latex_show_pagerefs = False

# If true, show URL addresses after external links.
# latex_show_urls = False

# Documents to append as an appendix to all manuals.
# latex_appendices = []

# If false, no module index is generated.
# latex_domain_indices = True


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [("index", "frepple", "frePPLe Documentation", ["frePPLe bv"], 1)]

# If true, show URL addresses after external links.
# man_show_urls = False

# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        "index",
        "frePPLe",
        "frePPLe Documentation",
        "frePPLe bv",
        "frePPLe",
        "One line description of project.",
        "Miscellaneous",
    )
]

html_baseurl = "https://your-site.com/docs/"

# Documents to append as an appendix to all manuals.
# texinfo_appendices = []

# If false, no module index is generated.
# texinfo_domain_indices = True

# How to display URL addresses: 'footnote', 'no', or 'inline'.
# texinfo_show_urls = 'footnote'

# If true, do not generate a @detailmenu in the "Top" node's menu.
# texinfo_no_detailmenu = False

# Redirecting old documentation pages to the new ones
redirects = {
    "videos/index": "../../a-day-in-the-life/index.html",
    "videos/demand-forecasting/check-forecast-accuracy": "../../a-day-in-the-life/demand-forecasting/check-forecast-accuracy.html",
    "videos/demand-forecasting/filter-outliers": "../../a-day-in-the-life/demand-forecasting/filter-outliers.html",
    "videos/demand-forecasting/forecast-new-item": "../../a-day-in-the-life/demand-forecasting/forecast-new-item.html",
    "videos/demand-forecasting/share-forecast": "../../a-day-in-the-life/demand-forecasting/share-forecast.html",
    "videos/demand-forecasting/compare-forecasts": "../../a-day-in-the-life/demand-forecasting/compare-forecasts.html",
    "videos/demand-forecasting/forecast-discontinued-item": "../../a-day-in-the-life/demand-forecasting/forecast-discontinued-item.html",
    "videos/demand-forecasting/index": "../../a-day-in-the-life/demand-forecasting/index.html",
    "videos/demand-forecasting/upload-forecast-values": "../../a-day-in-the-life/demand-forecasting/upload-forecast-values.html",
    "videos/inventory-planning/apply-policy-to-segment": "../../a-day-in-the-life/inventory-planning/apply-policy-to-segment.html",
    "videos/inventory-planning/identify-excess-inventory": "../../a-day-in-the-life/material-planning/identify-excess-inventory.html",
    "videos/inventory-planning/identify-stockout-risk": "../../a-day-in-the-life/material-planning/identify-stockout-risk.html",
    "videos/inventory-planning/apply-reorder-quantity-override": "../../a-day-in-the-life/inventory-planning/apply-reorder-quantity-override.html",
    "videos/inventory-planning/identify-expedite": "../../a-day-in-the-life/material-planning/identify-expedite.html",
    "videos/inventory-planning/index": "../../a-day-in-the-life/inventory-planning/index.html",
    "videos/inventory-planning/apply-safety-stock-override": "../../a-day-in-the-life/inventory-planning/apply-safety-stock-override.html",
    "videos/inventory-planning/identify-rebalancing": "../../a-day-in-the-life/material-planning/identify-rebalancing.html",
    "videos/inventory-planning/review-inventory-across-network": "../../a-day-in-the-life/material-planning/review-inventory-across-network.html",
    "videos/production-planning/check-impact-of-rush-orders": "../../a-day-in-the-life/production-planning/check-impact-of-rush-orders.html",
    "videos/production-planning/identify-expedite": "../../a-day-in-the-life/production-planning/identify-expedite.html",
    "videos/production-planning/prioritize-sales-order": "../../a-day-in-the-life/production-planning/prioritize-sales-order.html",
    "videos/production-planning/review-late-orders": "../../a-day-in-the-life/production-planning/review-late-orders.html",
    "videos/production-planning/define-operator-shifts": "../../a-day-in-the-life/production-planning/define-operator-shifts.html",
    "videos/production-planning/index": "../../a-day-in-the-life/production-planning/index.html",
    "videos/production-planning/quote-delivery-date": "../../a-day-in-the-life/demand-forecasting/quote-delivery-date.html",
    "videos/production-planning/unconstrained-requirements": "../../a-day-in-the-life/production-planning/unconstrained-requirements.html",
    "videos/production-planning/identify-bottleneck-resources": "../../a-day-in-the-life/production-planning/identify-bottleneck-resources.html",
    "videos/production-planning/optimize-plan-in-gantt-chart": "../../a-day-in-the-life/production-planning/optimize-plan-in-gantt-chart.html",
    "videos/production-planning/reassign-resource": "../../a-day-in-the-life/production-planning/reassign-resource.html",
    "videos/production-planning/update-machine-breakdown": "../../a-day-in-the-life/production-planning/update-machine-breakdown.html",
}
