.\"
.\" Copyright (C) 2009-2013 by frePPLe bvba
.\"
.\" This library is free software; you can redistribute it and/or modify it
.\" under the terms of the GNU Affero General Public License as published
.\" by the Free Software Foundation; either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This library is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero
.\" General Public License for more details.
.\"
.\" You should have received a copy of the GNU Affero General Public
.\" License along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\"
.TH "FREPPLE" "1" "August 2013" "frePPLe" ""
.SH "NAME"
frepple \- open source production planning and scheduling
.br
.SH "SYNOPSIS"
.B frepple [options]
.I <files>
.br
.B frepple [options]
.I <directories>
.br
.B frepple [options]

.SH "DESCRIPTION"
FrePPLe is an open source production planning and scheduling application.
.P
This program reads XML input data, and also embeds a Python interpeter to
execute instructions in the Python language.
.P
The input data can be provided in the following ways:
  - Passing one or more XML files.
  - Passing one or more directories as arguments.
    The program will process all files with the extension '.xml' found
    in the directories in alphabetical order.
  - Passing one or more Python files with the extension '.py'.
    The Python commands are executed in the embedded interpreter.
  - When passing no file or directory arguments, input will be read
    from the standard input. XML data can be redirected or piped to the
    application.

.SH OPTIONS
.TP
.BI "\-validate \-v"
Validate the xml input for correctness.
.TP
.BI "\-check \-c"
Only validate the input, without executing the content.
.TP
.BI "\-? \-h \-help"
Show instructions.

.SH ENVIRONMENT
.TP
FREPPLE_HOME
Optionally points to a directory where the initialization
files will be searched.

.SH FILES
.TP
.TP
\&./frepple.xsd $FREPPLE_HOME/frepple.xsd /usr/share/frepple/frepple.xsd
XML Schema definition for validation of the XML input data. The first file 
with the name frepple.xsd in the above sequence is processed.

.SH RETURNS
0 when successful, non-zero in case of errors

.SH "AUTHORS"
.B FrePPLe
is developed as Open Source under the AGPL license, v3 or later.

The authors and contributors are listed on https://frepple.com.
