.\"
.\" Copyright (C) 2009-2013 by frePPLe bv
.\"
.\" Permission is hereby granted, free of charge, to any person obtaining a copy
.\" of this software and associated documentation files (the "Software"), to deal
.\" in the Software without restriction, including without limitation the rights
.\" to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
.\" copies of the Software, and to permit persons to whom the Software is
.\" furnished to do so, subject to the following conditions:
.\"
.\" The above copyright notice and this permission notice shall be included in all
.\" copies or substantial portions of the Software.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
.\" IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
.\" FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
.\" AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
.\" LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
.\" OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
.\" SOFTWARE.
.\"
.TH "FREPPLE" "1" "April 2023" "frePPLe" ""
.SH "NAME"
frepple \- open source production planning and scheduling
.br
.SH "SYNOPSIS"
.B frepple [options]
.I <files>
.br
.B frepple [options]
.I <directories>
.br
.B frepple [options]

.SH "DESCRIPTION"
FrePPLe is an open source production planning and scheduling application.
.P
This program reads XML input data, and also embeds a Python interpeter to
execute instructions in the Python language.
.P
The input data can be provided in the following ways:
  - Passing one or more XML files.
  - Passing one or more directories as arguments.
    The program will process all files with the extension '.xml' found
    in the directories in alphabetical order.
  - Passing one or more Python files with the extension '.py'.
    The Python commands are executed in the embedded interpreter.
  - When passing no file or directory arguments, input will be read
    from the standard input. XML data can be redirected or piped to the
    application.

.SH OPTIONS
.TP
.BI "\-validate \-v"
Validate the xml input for correctness.
.TP
.BI "\-check \-c"
Only validate the input, without executing the content.
.TP
.BI "\-? \-h \-help"
Show instructions.

.SH ENVIRONMENT
.TP
FREPPLE_HOME
Optionally points to a directory where the initialization
files will be searched.

.SH FILES
.TP
.TP
\&./frepple.xsd $FREPPLE_HOME/frepple.xsd /usr/share/frepple/frepple.xsd
XML Schema definition for validation of the XML input data. The first file
with the name frepple.xsd in the above sequence is processed.

.SH RETURNS
0 when successful, non-zero in case of errors

.SH "AUTHORS"
.B FrePPLe
is developed as Open Source under the MIT license.

The authors and contributors are listed on https://frepple.com.
