.\"
.\" Copyright (C) 2009 by Johan De Taeye
.\"
.\" This library is free software; you can redistribute it and/or modify it
.\" under the terms of the GNU Lesser General Public License as published
.\" by the Free Software Foundation; either version 2.1 of the License, or
.\" (at your option) any later version.
.\"
.\" This library is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser
.\" General Public License for more details.
.\"
.\" You should have received a copy of the GNU Lesser General Public
.\" License along with this library; if not, write to the Free Software
.\" Foundation Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA
.\"
.\" file : $URL$
.\" revision : $LastChangedRevision$  $LastChangedBy$
.\" date : $LastChangedDate$
.TH "FREPPLE" "1" "July 2009" "frePPLe" ""
.SH "NAME"
frepple \- a lightweight tool for production planning
.br
.SH "SYNOPSIS"
.B frepple [options]
.I <files>
.br
.B frepple [options]
.I <directories>
.br
.B frepple [options]

.SH "DESCRIPTION"
FrePPLe is a lightweight open source framework that easily and quickly 
solves production planning problems. The primary focus is on the discrete 
manufacturing industry.
.P
This program reads XML input data, and executes the modeling and
Python commands included in them.
.P
The xml input can be provided in the following ways:
  - Passing one or more XML files
  - Passing one or more directories as arguments.
    The program will process all files with the extension '.xml' found
    in the directories.
  - When passing no file or directory arguments, input will be read
    from the standard input. XML data can be redirected or piped to the
    application.

.SH OPTIONS
.TP
.BI "\-validate \-v"
Validate the xml input for correctness.
.TP
.BI "\-check \-c"
Only validate the input, without executing the content.
.TP
.BI "\-? \-h \-help"
Show instructions.

.SH ENVIRONMENT
.TP
FREPPLE_HOME
Optionally points to a directory where the initialization
files will be searched.

.SH FILES
.TP
/usr/share/frepple/init.xml
XML data automatically loaded upon startup.
.TP
/usr/share/frepple/frepple.xsd
XML Schema definition for validation of the input data.
.TP
/usr/share/frepple/init.py
Python commands executed automatically upon startup.

.SH RETURNS
0 when succesfull, non-zero in case of errors

.SH "AUTHORS"
.B FrePPLe
is developed as Open Source under the LGPL license.

The authors and contributors are listed on http://www.frepple.com.

