# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execute', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='logfile',
            field=models.TextField(editable=False, max_length=200, null=True, verbose_name='logfile'),
        ),
    ]
