# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execute', '0002_task_logfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(db_index=True, editable=False, max_length=50, verbose_name='name'),
        ),
    ]
