# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import freppledb.common.fields


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0022_demand_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationplan',
            name='material',
            field=freppledb.common.fields.JSONBField(blank=True, default='{}', editable=False, null=True),
        ),
        migrations.AddField(
            model_name='operationplan',
            name='resource',
            field=freppledb.common.fields.JSONBField(blank=True, default='{}', editable=False, null=True),
        ),
    ]
