# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-12-04 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0033_lastmodified_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdistribution',
            name='sizemaximum',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='A maximum shipping quantity', max_digits=20, null=True, verbose_name='size maximum'),
        ),
        migrations.AddField(
            model_name='itemsupplier',
            name='sizemaximum',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='A maximum purchasing quantity', max_digits=20, null=True, verbose_name='size maximum'),
        ),
    ]
