# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-07-10 10:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0040_autofence_parameter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buffer',
            options={'ordering': ['item', 'location'], 'verbose_name': 'buffer', 'verbose_name_plural': 'buffers'},
        ),
        migrations.RemoveField(
            model_name='buffer',
            name='name',
        ),
        migrations.AddField(
            model_name='buffer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='identifier'),
            preserve_default=False,
        ),
    ]
